### ISSUE TITLE
No output files built when installing via "yarn install"

### ISSUE THREAD

**Issue by jot-the-coder** [d9c4/typescript-roman-numbers-converter#1]
Hi Davide,

Just I found your package when browsing in npmjs.com and tried a little bit. However, my TypeScript compiler told me that your package cannot be used. Then I checked the "node_module/typescript-roman-numbers-converter" folder, there was only very few files there, like "package.json". From your codes it seems "lib" folder will be built after TS compile but it's not found there.

I'm not familar with NPM publish process, but I guess it would be a publishing problem, like ignoring the "lib" folder during "yarn install"? Like missing an ".npmignore" file so that ".gitignore" is used? Though I just tried it very briefly, and didn't try installation with "npm" CLI so I cannot say that for sure.

Thanks very much.

P.S. Testing under
- node: v18.12.1;
- yarn: v3.4.1;

**Comment by d9c4** [comment]
Hello!
Thanks for using my library, I'll do a deep check as soon I can but after a first glance I think you're right about the publishing problem. I'll keep you updated!

Thanks!

**Comment by d9c4** [comment]
Hello @jot-the-coder , I've just released a new version of the package (1.2.3) and done a few tests.
Please, update to this version and let me know if somehow the ts compiler can now find the lib folder. I'll keep this issue open.
Thanks!

**Comment by d9c4** [comment]
Solved

**Comment by jot-the-coder** [comment]
Thanks very much! I shall check out the new release after the tasks on hand finished.
